#pragma once

typedef enum {
  MENU_UNDEFINED = 0,
  MENU_START_SERVER_GUI,
  MENU_START_SERVER_NOGUI,
  MENU_ONLINE_HELP,
  MENU_JAVA_INSTALL,
  MENU_LANGUAGE_SETTINGS,
  MENU_FRP_INSTALL,
  MENU_EXIT,
  MENU_DISCLAIMER
} menu_selection_t;
